import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Reviewed Memory: agents PROPOSE knowledge, humans APPROVE it, `sync` writes
 * the approved set into CLAUDE.md/AGENTS.md/GEMINI.md as a marked block —
 * so every agent CLI that reads those files gets it, git distributes it,
 * and driftlint's own checks keep verifying it against the code.
 */

const DIR = ".agent-memory";
const PROPOSALS = path.join(DIR, "proposals");
const APPROVED = path.join(DIR, "approved");
const START = "<!-- driftlint-memory:start — generated by `driftlint memory sync`; edit entries under .agent-memory/, not here -->";
const END = "<!-- driftlint-memory:end -->";

export interface MemoryEntry {
  file: string;
  text: string;
  scope: string;
  confidence: string;
  evidence: string;
  created: string;
  source: string;
}

function parseEntry(file: string, content: string): MemoryEntry {
  const fm = new Map<string, string>();
  let body = content;
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(content);
  if (m?.[1] !== undefined) {
    body = content.slice(m[0].length);
    for (const line of m[1].split(/\r?\n/)) {
      const kv = /^([A-Za-z_-]+):\s*(.*)$/.exec(line);
      if (kv?.[1]) fm.set(kv[1].toLowerCase(), (kv[2] ?? "").trim());
    }
  }
  return {
    file,
    text: body.trim(),
    scope: fm.get("scope") ?? "repo",
    confidence: fm.get("confidence") ?? "medium",
    evidence: fm.get("evidence") ?? "",
    created: fm.get("created") ?? "",
    source: fm.get("source") ?? "",
  };
}

function readDirEntries(root: string, rel: string): MemoryEntry[] {
  const dir = path.join(root, rel);
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => parseEntry(path.join(rel, f), fs.readFileSync(path.join(dir, f), "utf8")));
}

export function listEntries(root: string): { proposals: MemoryEntry[]; approved: MemoryEntry[] } {
  return { proposals: readDirEntries(root, PROPOSALS), approved: readDirEntries(root, APPROVED) };
}

export function propose(
  root: string,
  opts: { text: string; scope?: string; evidence?: string; source?: string },
): string {
  const dir = path.join(root, PROPOSALS);
  fs.mkdirSync(dir, { recursive: true });
  let slug =
    opts.text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").split("-").slice(0, 6).join("-") || "entry";
  let name = `${slug}.md`;
  for (let n = 2; fs.existsSync(path.join(dir, name)); n++) name = `${slug}-${n}.md`;
  const created = new Date().toISOString().slice(0, 10);
  const content = `---\nscope: ${opts.scope ?? "repo"}\nconfidence: medium\nevidence: ${opts.evidence ?? ""}\ncreated: ${created}\nsource: ${opts.source ?? "manual"}\n---\n${opts.text.trim()}\n`;
  const p = path.join(dir, name);
  fs.writeFileSync(p, content);
  return path.join(PROPOSALS, name);
}

export function approve(root: string, entryFile: string): string {
  const dest = path.join(root, APPROVED, path.basename(entryFile));
  fs.mkdirSync(path.join(root, APPROVED), { recursive: true });
  fs.renameSync(path.join(root, entryFile), dest);
  return path.join(APPROVED, path.basename(entryFile));
}

const SYNC_TARGETS = ["CLAUDE.md", "AGENTS.md", "GEMINI.md"];

/** Write the approved set into every context file present (create CLAUDE.md if none). */
export function sync(root: string): string[] {
  const { approved } = listEntries(root);
  const lines = approved.map((e) => {
    const meta = [e.scope !== "repo" ? `scope: ${e.scope}` : "", e.evidence ? `evidence: ${e.evidence}` : ""]
      .filter(Boolean)
      .join(", ");
    return `- ${e.text.replace(/\s*\n\s*/g, " ")}${meta ? ` _(${meta})_` : ""}`;
  });
  const block = `${START}\n## Team memory (reviewed)\n${lines.length ? lines.join("\n") : "_(no approved entries yet)_"}\n${END}`;

  let targets = SYNC_TARGETS.filter((t) => fs.existsSync(path.join(root, t)));
  if (targets.length === 0) {
    fs.writeFileSync(path.join(root, "CLAUDE.md"), `${block}\n`);
    return ["CLAUDE.md"];
  }
  for (const t of targets) {
    const p = path.join(root, t);
    const content = fs.readFileSync(p, "utf8");
    const startIdx = content.indexOf(START);
    const endIdx = content.indexOf(END);
    const next =
      startIdx !== -1 && endIdx !== -1
        ? content.slice(0, startIdx) + block + content.slice(endIdx + END.length)
        : `${content.replace(/\n*$/, "")}\n\n${block}\n`;
    fs.writeFileSync(p, next);
  }
  return targets;
}

export async function runMemoryCli(argv: string[]): Promise<number> {
  const sub = argv[0];
  const root = process.cwd();
  const flag = (name: string): string | undefined => {
    const i = argv.indexOf(`--${name}`);
    return i !== -1 ? argv[i + 1] : undefined;
  };

  if (sub === "propose") {
    const text = flag("text");
    if (!text) {
      console.error('driftlint memory propose --text "<one fact>" [--scope <path>] [--evidence <file:line|commit>] [--source <agent>]');
      return 2;
    }
    const p = propose(root, { text, scope: flag("scope"), evidence: flag("evidence"), source: flag("source") });
    console.log(`proposed: ${p} — review with \`driftlint memory review\``);
    return 0;
  }

  if (sub === "list") {
    const { proposals, approved } = listEntries(root);
    for (const e of approved) console.log(`approved  ${e.file}  ${e.text.slice(0, 80)}`);
    for (const e of proposals) console.log(`PENDING   ${e.file}  ${e.text.slice(0, 80)}`);
    console.log(`${approved.length} approved, ${proposals.length} pending`);
    return 0;
  }

  if (sub === "review") {
    const { proposals } = listEntries(root);
    if (proposals.length === 0) {
      console.log("no pending proposals.");
      return 0;
    }
    const yes = argv.includes("--yes");
    if (!yes && !process.stdin.isTTY) {
      console.error(`${proposals.length} pending proposals — run in a terminal, or use --yes to approve all.`);
      return 1;
    }
    let rl: import("node:readline/promises").Interface | null = null;
    if (!yes) {
      const readline = await import("node:readline/promises");
      rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    }
    let approved = 0;
    for (const e of proposals) {
      let action = "a";
      if (rl) {
        console.log(`\n${e.text}\n  (${[e.scope !== "repo" ? `scope: ${e.scope}` : "", e.evidence && `evidence: ${e.evidence}`, e.source && `source: ${e.source}`].filter(Boolean).join(", ") || "no metadata"})`);
        action = (await rl.question("[a]pprove / [r]eject / [s]kip? ")).trim().toLowerCase();
      }
      if (action.startsWith("a")) {
        approve(root, e.file);
        approved++;
      } else if (action.startsWith("r")) {
        fs.unlinkSync(path.join(root, e.file));
        console.log("rejected (deleted).");
      }
    }
    rl?.close();
    if (approved > 0) {
      const targets = sync(root);
      console.log(`${approved} approved → synced into ${targets.join(", ")}`);
    }
    return 0;
  }

  if (sub === "sync") {
    const targets = sync(root);
    console.log(`synced approved memory into ${targets.join(", ")}`);
    return 0;
  }

  console.error("driftlint memory <propose|review|list|sync>");
  return 2;
}
